name: Build

on: [push]

jobs:
  BuildCuda:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: Jimver/cuda-toolkit@v0.2.26
      id: cuda-toolkit
      with:
        cuda: '12.9.0'
        method: 'network'
        sub-packages: '["nvcc", "thrust"]'
    - run: sudo apt install -y cmake build-essential g++
    - run: python -m pip install scikit-build wheel ninja
    - run: python setup.py bdist_wheel

